import { ThemeProvider } from "just-styled";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<ThemeProvider theme={{ tokens: { colors: { red: "#dc2626" } } }}>
				<body>{children}</body>
			</ThemeProvider>
		</html>
	);
}
