name: TypeCheck

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: pnpm install
        shell: bash
        run: |
          pnpm install --frozen-lockfile
      - name: Run test
        run: pnpm run test:coverage
      - name: Show coverage
        if: ${{ always() && github.event_name == 'pull_request' }}
        uses: davelosert/vitest-coverage-report-action@v2
